"""
Data models for the content automation pipeline.

Phase 1 — core types for planner, generator, validator, approval, and publisher.
All state lives in the posts/post_versions/post_review_actions tables in agency.db.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


# ── Enums ─────────────────────────────────────────────────────────────────────

class PostType(str, Enum):
    """The six content categories the planner rotates through."""
    VIRAL_ATTENTION   = "viral_attention"
    CONVERSION_ORDER = "conversion_order"
    LOCAL_DISCOVERY  = "local_discovery"
    TOURIST_DISCOVERY = "tourist_discovery"
    MENU_HIGHLIGHT   = "menu_highlight"
    SEASONAL_TREND   = "seasonal_trend"


class PostStatus(str, Enum):
    """
    Full pipeline state machine.

    planned → researching → drafted → validation_failed → pending_approval
           → approved → rejected → revision_requested → publishing → published
           → publish_failed
    """
    PLANNED            = "planned"
    RESEARCHING         = "researching"
    DRAFTED             = "drafted"
    VALIDATION_FAILED  = "validation_failed"
    PENDING_APPROVAL   = "pending_approval"
    APPROVED           = "approved"
    REJECTED           = "rejected"
    REVISION_REQUESTED = "revision_requested"
    PUBLISHING         = "publishing"
    PUBLISHED          = "published"
    PUBLISH_FAILED     = "publish_failed"


class RiskLevel(str, Enum):
    LOW    = "low"
    MEDIUM = "medium"
    HIGH   = "high"
    BLOCK  = "block"


# ── Content Plan ───────────────────────────────────────────────────────────────

class ContentPlan(BaseModel):
    """
    Output of the planner: one planned post slot.

    The 3-posts/day rule:
      - Slot 0 (morning): viral_attention
      - Slot 1 (midday):  conversion_order
      - Slot 2 (evening): local_discovery | tourist_discovery | menu_highlight | seasonal_trend
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    slot: int = Field(ge=0, le=2, description="0=morning, 1=midday, 2=evening")
    post_type: PostType
    topic: str = Field(description="Short topic summary, e.g. 'Weekend dining guide for Stockton families'")
    title: str = Field(description="Draft title generated by the planner")
    slug: str = Field(description="URL-safe slug")
    meta_description: str = Field(max_length=160)
    target_audience: str
    primary_keyword: str
    secondary_keywords: list[str] = Field(default_factory=list)
    geographic_scope: str = Field(default="local", description="local | regional | state | national")
    # Why was this topic chosen — for human reviewer
    source_notes: str = Field(default="", description="Why this topic was selected (for audit)")
    # Trend data (may be empty in Phase 1)
    trend_signal_id: Optional[str] = None
    relevance_score: Optional[float] = None
    # Scheduling
    scheduled_for: Optional[str] = Field(None, description="ISO-8601 datetime")
    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


# ── Content Draft ───────────────────────────────────────────────────────────────

class ContentDraft(BaseModel):
    """
    Output of generator: a complete post ready for validation.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    plan_id: str
    version: int = Field(default=1, ge=1)

    # Core fields
    title: str
    slug: str
    meta_description: str = Field(max_length=160)
    excerpt: str = Field(max_length=300)
    body_markdown: str
    body_html: Optional[str] = None
    cta_text: str = Field(default="Visit Us Tonight")
    cta_url: str = Field(default="https://www.rawsushibar.com")

    # SEO
    seo_title: str
    focus_keyword: str
    secondary_keywords: list[str] = Field(default_factory=list)
    internal_links: list[str] = Field(default_factory=list)

    # Image
    image_asset_id: Optional[str] = None
    image_url: Optional[str] = None
    image_prompt: Optional[str] = None

    # Metadata
    post_type: PostType
    target_audience: str
    source_notes: str = Field(default="", description="Why this topic was chosen + source data used")
    raw_content: Optional[str] = None  # unparsed LLM output for debugging

    # Validation
    validation_result: Optional[ValidationResult] = None

    # Timestamps
    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    class Config:
        use_enum_values = True


# ── Validation Result ────────────────────────────────────────────────────────────

class ValidationResult(BaseModel):
    """
    Multi-layer validation output from validator.py.
    """
    passed: bool = Field(description="True only if hard + quality + policy all pass")
    risk_level: RiskLevel = RiskLevel.LOW

    # Layer results
    hard_valid: bool = True
    hard_issues: list[str] = Field(default_factory=list, description="Hard fail reasons")
    quality_score: float = Field(ge=0.0, le=100.0, default=0.0)
    quality_issues: list[str] = Field(default_factory=list)
    policy_passed: bool = True
    policy_issues: list[str] = Field(default_factory=list)

    # Overall decision
    publish_decision: str = Field(default="PASS")  # PASS | REVIEW | FAIL
    editor_notes: str = Field(default="")

    # Specific flags
    fabricated_data_detected: bool = False
    culturally_inappropriate_detected: bool = False
    duplicate_topic_detected: bool = False
    keyword_stuffing_detected: bool = False

    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


# ── Trend Signal ────────────────────────────────────────────────────────────────

class TrendSignal(BaseModel):
    """
    A scored trend input for the planner.

    Fields populated by trend_engine (Phase 2).
    Phase 1 uses these as empty placeholders.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    topic: str
    geography_scope: str = "local"   # local | regional | state | national
    category: str = "food"           # food | travel | community | seasonal | local_events
    source_type: str = ""            # headline_api | event_feed | seasonal_calendar
    source_reference: str = ""
    relevance_score: float = Field(ge=0.0, le=1.0, default=0.0)
    risk_level: RiskLevel = RiskLevel.LOW
    publishable: bool = True
    used_at: Optional[str] = None
    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


# ── Approval Action ─────────────────────────────────────────────────────────────

class ApprovalAction(BaseModel):
    """Record of a human or system action on a post."""
    post_id: str
    version_id: Optional[str] = None
    actor: str
    actor_type: str = "human_reviewer"  # human_reviewer | ai_agent | system
    action: str  # approve | reject | request_revision | publish | fail
    comment: str = ""
    from_status: Optional[str] = None
    to_status: Optional[str] = None
    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


# ── Publish Result ──────────────────────────────────────────────────────────────

class PublishResult(BaseModel):
    """Output from the publisher."""
    success: bool
    mode: str = "git_commit"  # git_commit | manual_export
    slug: str
    filepath: Optional[str] = None
    html_url: Optional[str] = None
    published_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    git_commit: Optional[str] = None
    error: Optional[str] = None


# ── Daily Job Status ─────────────────────────────────────────────────────────────

class DailyJobStatus(BaseModel):
    """Aggregate status of the 3-posts/day pipeline for a given date."""
    date: str  # YYYY-MM-DD
    brand: str = "raw"
    slots: dict[int, dict] = Field(
        default_factory=lambda: {0: {}, 1: {}, 2: {}}
    )
    created_plans: int = 0
    completed_drafts: int = 0
    validation_passes: int = 0
    in_approval_queue: int = 0
    published_today: int = 0
    errors: list[str] = Field(default_factory=list)